import { useNavigate } from 'react-router-dom'
import Icon from './Icons'

const COLORS = {
  bg: '#F8FAFC',
  card: '#FFFFFF',
  border: '#E2E8F0',
  purple: '#6B21A8',
  text: '#0F172A',
  textMuted: '#64748B',
}

const SECTIONS = [
  {
    title: '1. Introduction',
    body: `Welcome to Traveler.com.\n\nTraveler.com is a travel technology platform operated by RB GLOBAL, created to help you discover, book, and manage hotels, flights, buses, trains, tours, and event centers.\n\nThis Customer Privacy Policy explains how we collect, use, store, and protect your personal information when you use Traveler.com as a customer. By creating a customer account, you agree to this Privacy Policy.`,
  },
  {
    title: '2. Information We Collect',
    body: `We may collect information you provide directly, information generated by your bookings, and technical information from your device, as described in the sections below.`,
  },
  {
    title: '3. Account Information',
    body: `When you create a customer account, we collect:\n• Full name\n• Email address\n• Phone number\n• Password (stored securely, never in plain text)\n• Profile photo (optional)`,
  },
  {
    title: '4. Booking Information',
    body: `When you make a booking, we collect:\n• Hotel, flight, bus, train, tour, or event center selected\n• Booking dates and times\n• Number of travelers or guests\n• Identification details where required for check-in or boarding\n• Booking status and history`,
  },
  {
    title: '5. Payment Information',
    body: `We collect payment-related records including:\n• Traveler Wallet balance and transaction history\n• Payment method used\n• Payment status\n\nTraveler.com does not store your complete debit or credit card details.`,
  },
  {
    title: '6. Device and Technical Information',
    body: `We may collect:\n• Device model and operating system\n• Browser type and version\n• IP address\n• App version\n• Login activity\n\nThis helps us keep your account secure and improve platform performance.`,
  },
  {
    title: '7. Location Information',
    body: `With your permission, we may use approximate location information to show relevant nearby travel options and improve search results. You can control location access from your device settings.`,
  },
  {
    title: '8. How We Use Your Information',
    body: `We use your information to:\n• Process and confirm your bookings\n• Verify your identity where required\n• Prevent fraud and protect your account\n• Send booking confirmations and updates\n• Provide customer support\n• Improve our platform and services\n• Recommend relevant hotels, flights, and travel options`,
  },
  {
    title: '9. How We Share Information',
    body: `We only share your information when necessary to provide our services, and never sell your personal information to advertisers.`,
  },
  {
    title: '10. Travel and Service Providers',
    body: `To fulfill your booking, we share the necessary booking details (such as your name and booking reference) with the relevant hotel, airline, bus operator, train operator, tour operator, or event center.`,
  },
  {
    title: '11. Payment Providers',
    body: `Payment processors handle your payment transactions securely. Traveler.com shares only the information necessary to process your payment and does not share your full card details with any party, including itself.`,
  },
  {
    title: '12. Data Security',
    body: `We use industry-standard security measures including encryption, secure authentication, and access controls to protect your information.\n\nWhile we work hard to protect your data, no online service can guarantee 100% security.`,
  },
  {
    title: '13. Data Retention',
    body: `We retain your account and booking information for as long as your account is active, or as needed to comply with legal obligations, resolve disputes, and enforce our agreements.`,
  },
  {
    title: '14. Cookies and Similar Technologies',
    body: `Traveler.com uses cookies and similar technologies to keep you signed in, remember your preferences, and improve your experience. You may disable cookies through your browser settings, though some features may not work correctly.`,
  },
  {
    title: '15. Your Privacy Rights',
    body: `Depending on your location, you may have the right to:\n• Access your personal data\n• Correct inaccurate information\n• Request a copy of your data\n• Request deletion of your account\n\nSome information may be retained where required by law.`,
  },
  {
    title: '16. Account Deletion',
    body: `You can request account deletion from Settings → Account Data → Request account deletion. Once processed, your profile and saved data will be removed; some booking records may be retained where required by law.`,
  },
  {
    title: "17. Children's Privacy",
    body: `Traveler.com is not intended for children under the age required by applicable law without parental or guardian consent.`,
  },
  {
    title: '18. Changes to This Privacy Policy',
    body: `We may update this Privacy Policy from time to time. When significant changes are made, we will notify you through the app or by email where appropriate.`,
  },
  {
    title: '19. Contact Us',
    body: `For privacy-related questions, data requests, or concerns, please reach out through Traveler.com's Help & Support section within the app.`,
  },
]

export default function CustomerPrivacyPolicy() {
  const navigate = useNavigate()

  return (
    <div style={{ minHeight: '100vh', background: COLORS.bg, maxWidth: '480px', margin: '0 auto', paddingBottom: '40px' }}>

      <div style={{
        padding: '18px 20px', display: 'flex', alignItems: 'center', gap: '14px',
        background: COLORS.card, position: 'sticky', top: 0, zIndex: 10, boxShadow: '0 1px 4px rgba(0,0,0,0.05)'
      }}>
        <div onClick={() => navigate(-1)} style={{ cursor: 'pointer', display: 'flex' }}>
          <Icon name="arrowLeft" size={22} color={COLORS.text} />
        </div>
        <h1 style={{ fontSize: '17px', fontWeight: 800, color: COLORS.text }}>Privacy Policy</h1>
      </div>

      <div style={{ padding: '16px' }}>
        <p style={{ fontSize: '11.5px', color: COLORS.textMuted, marginBottom: '16px' }}>Effective Date: July 31, 2026</p>

        <div style={{ background: COLORS.card, borderRadius: '16px', padding: '18px', marginBottom: '16px', boxShadow: '0 2px 10px rgba(0,0,0,0.06)' }}>
          {SECTIONS.map((s, i) => (
            <div key={s.title} style={{ marginBottom: i < SECTIONS.length - 1 ? '20px' : 0 }}>
              <p style={{ fontSize: '14px', fontWeight: 800, color: COLORS.purple, marginBottom: '8px' }}>{s.title}</p>
              <p style={{ fontSize: '12.5px', color: COLORS.text, lineHeight: 1.7, whiteSpace: 'pre-line' }}>{s.body}</p>
            </div>
          ))}
        </div>

        <div style={{ background: '#F5F3FF', borderRadius: '16px', padding: '18px', textAlign: 'center' }}>
          <p style={{ fontSize: '13px', fontWeight: 800, color: COLORS.purple, marginBottom: '6px' }}>Your Data, Respected</p>
          <p style={{ fontSize: '12.5px', color: COLORS.text, lineHeight: 1.6 }}>
            We collect only what we need to get you where you're going, and protect it like it's our own.
          </p>
        </div>
      </div>
    </div>
  )
}
